### ISSUE TITLE
Add php-sqlite3 to dependencies

### ISSUE THREAD

**Issue by vinc** [AssociationInfoclimat/StatIC-WeeWX#1]
Hi,

The README suggest installing `git` and `php-cli`. It could also add a suggestion to install the required package for the database, like `php-sqlite3` for SQLite3.

Otherwise you get this when running it:

```
$ php /home/pi/weewx-infoclimat/static.php --debug=true
PHP Fatal error:  Uncaught Error: Class 'SQLite3' not found in /home/pi/weewx-infoclimat/static.php:43
Stack trace:
#0 {main}
  thrown in /home/pi/weewx-infoclimat/static.php on line 43
```

Unrelated but while I was looking at the README I noticed that the path to `static.php` is different in the crontab example. It should be identical to the previous ones. And it should also set the `--debug` argument otherwise you get a PHP notice.

While I'm here I'd also suggest rewriting this script in Python as it's already present to run weewx and maybe renaming the repo `weewx-infoclimat`.

Cheers

**Comment by RaphaelChochon** [comment]
Bonjour,

Merci pour ces petites corrections qui viennent d'être faites 
En ce qui concerne la réécriture du script en Python, nous avons fait selon les préférences de programmation des personnes disponibles pour le créer, d'où son écriture en PHP.
Mais toute contribution est bonne à prendre ;)

Amicalement
